### ISSUE TITLE
flux-local build failes for helm OCI chart

### ISSUE THREAD

**Issue by TheKangaroo** [allenporter/flux-local#183]
flux-local works perfectly for our use cases, but I cannot get `flux-local build  --enable-helm` working when I have a helm chart which is oci hosted in my config.

Example:
 I followed the install [instructions](https://docs.gitops.weave.works/docs/installation/weave-gitops/) for the weaveworks-gitops dashboard which leaves me with the following resources:
 ```
 ---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  annotations:
    metadata.weave.works/description: This is the source location for the Weave GitOps
      Dashboard's helm chart.
  labels:
    app.kubernetes.io/component: ui
    app.kubernetes.io/created-by: weave-gitops-cli
    app.kubernetes.io/name: weave-gitops-dashboard
    app.kubernetes.io/part-of: weave-gitops
  name: ww-gitops
  namespace: flux-system
spec:
  interval: 1h0m0s
  type: oci
  url: oci://ghcr.io/weaveworks/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  annotations:
    metadata.weave.works/description: This is the Weave GitOps Dashboard.  It provides
      a simple way to get insights into your GitOps workloads.
  name: ww-gitops
  namespace: flux-system
spec:
  chart:
    spec:
      chart: weave-gitops
      sourceRef:
        kind: HelmRepository
        name: ww-gitops
  interval: 1h0m0s
  values:
    adminUser:
      create: true
      passwordHash: <hash>
      username: admin
 ```
with this HelmRelease in my flux kustomization
```
flux-local build ./clusters/<clustername> --enable-helm --skip-crds
```
failes with the following error:
```
flux-local error:  Invalid <class 'flux_local.manifest.HelmChart'> missing sourceRef fields: {'apiVersion': 'helm.toolkit.fluxcd.io/v2beta1', 'kind': 'HelmRelease', 'metadata': {'name': 'ww-gitops', 'namespace': 'flux-system', 'annotations': {'config.kubernetes.io/index': '0', 'internal.config.kubernetes.io/index': '0'}}, 'spec': {'chart': {'spec': {'chart': 'weave-gitops', 'sourceRef': {'kind': 'HelmRepository', 'name': 'ww-gitops'}}}, 'interval': '1h0m0s', 'releaseName': 'ww-gitops'}}
```

It seems like this  error happens because of a missing namespace key under `spec.chart.spec.sourceRef`.
When I add the namespace key like `namespace: flux-system` I get another error:
```
Command '(None) helm template ww-gitops flux-system-ww-gitops/weave-gitops --namespace flux-system --skip-tests --values /var/folders/tj/25qdsj_n1bqfr1bwvj9hjqxw0000gq/T/tmp7zjtbv7u/flux-system-ww-gitops-values.yaml --registry-config /dev/null --repository-cache /var/folders/tj/25qdsj_n1bqfr1bwvj9hjqxw0000gq/T/tmplbwf5vh5 --repository-config /var/folders/tj/25qdsj_n1bqfr1bwvj9hjqxw0000gq/T/tmp7zjtbv7u/repository-config.yaml' failed with return code 1
Error: chart "weave-gitops" matching  not found in flux-system-ww-gitops index. (try 'helm repo update'): no chart name found
```
I don't know how to debug this further since flux-local seems to clean up my temp dir on the error.
