### ISSUE TITLE
Helm values from secrets/configmaps

### ISSUE THREAD

**Issue by TheKangaroo** [allenporter/flux-local#338]
We use kustomize to generate configmaps from `values.yaml` files for better readability over the inline `spec.values` in HelmReleases and reference them in the `spec.valuesFrom` array. 
These values will be ignored by flux-local on helm inflation because only the `spec.values` field is used (https://github.com/allenporter/flux-local/blob/main/flux_local/helm.py#L221).
I wonder if we could optionally (it is not guaranteed that the cm/secret is deployed via flux) pull in secret/cm values files if they exist in the content object.
I would like to try and implement this if it sounds like a valuable addition.
I will need some time to dig into the code though.

Example, this does not work at the moment:
`example.yaml`
```yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example
  namespace: example
spec:
  interval: 5m
  chart:
    spec:
      chart: example
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: example
        namespace: flux-system
      interval: 1m
  valuesFrom:
    - kind: ConfigMap
      name: example-values
      optional: true
```
`kustomization.yaml`
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - example.yaml
configMapGenerator:
  - files:
    - values.yaml=example-values.yaml
    name: example-values
    namespace: example
generatorOptions:
  disableNameSuffixHash: true
```
`example-values.yaml`
```yaml
image:
  repository: "..."
  tag: "..."
```
