### ISSUE TITLE
external GitRepository running into build error

### ISSUE THREAD

**Issue by Dariusch** [allenporter/flux-local#360]
Hello,

I was initially trying to test your CLI in our gitops repository but ran into errors:

```
flux-local error:  Error building Fluxtomization in '/Users/foo/gitops'  \
path 'manifests/monitoring/monitoring-config': Specified path is not a directory:  \
/Users/foo/gitops/manifests/monitoring/monitoring-config - \
Is a Kustomization pointing to a path that does not exist?
```

I believe it is because an external GitReoisitory source is unavailable locally.
We have quite a few of those external sources, it would be nice if you could support them at some point.

Here is a minimal example that runs into the error mentioned above.

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-source
  namespace: flux-system
spec:
  ref:
    tag: "v2.1.2"
  interval: 120m
  timeout: 60s
  url: https://github.com/fluxcd/flux2.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-dashboards
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./manifests/monitoring/monitoring-config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-source
  timeout: 10m
```

Not referencing the files in the Kustomization files will result in successful commands but incomplete diffs.

Thank you
