### ISSUE TITLE
Concurrency issues with flux build without kustomization.yaml

### ISSUE THREAD

**Issue by ansarhun** [allenporter/flux-local#483]
With version v4 I noticed that the `allenporter/flux-local/action/diff` action is started to fail.

In the error there are errors regarding the generation of the `kustomization.yaml` e.g.:

```
DEBUG:flux_local.command:Command 'flux build ks crds-traefik --dry-run --kustomization-file /dev/stdin --path /Users/ansar/Projects/home-ops/clusters/home --namespace flux-system' failed with return code 1
✗ kustomize build failed: kustomization.yaml is empty

DEBUG:flux_local.command:Command 'flux build ks flux-system --dry-run --kustomization-file /dev/stdin --path /Users/ansar/Projects/home-ops/clusters/home --namespace flux-system' failed with return code 1
✗ failed to generate kustomization.yaml: failed to save original kustomization.yaml: open /Users/ansar/Projects/home-ops/clusters/home/kustomization.yaml: no such file or directory <nil> <nil>
```

As the error occurs in different places for each run my guess is that it's related to flux build generating the `kustomization.yaml` file but as multiple build commands are run parallel they will collide on the same file.

To verify I changed the concurrency level to 1 in here: https://github.com/allenporter/flux-local/blob/main/flux_local/command.py#L17
and it seems to "solved" the issue.

**Comment by allenporter** [comment]
Yeah, i've seen `flux build` write files while running which previously kind of surprised me. Good find.

Does this mean that both kustomizations `crds-traefik` and `flux-system` both have a `path` of `clusters/home`? This means then that there are two kustomizations building the same directory at the same time, which is not something expected to happen.

**Comment by ansarhun** [comment]
My setup is using the same setup as `tests/testdata/cluster7` 
`clusters/home` contains the top-level `kustomize.toolkit.fluxcd.io/v1` `Kustomization`s

the `flux-system` is in the `clusters/home`

but for the `crds-traefik`: `clusters/home` contains a `crds.yaml`

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./flux/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
```

which looks like this:
```
☸ k0s-cluster in home-ops on  master [$!?] via 🐍 v3.11.6 (venv)
❯ ls -lah flux/crds
total 0
drwxr-xr-x  6 ansar  staff   192B Dec 30 20:02 .
drwxr-xr-x  8 ansar  staff   256B Sep  8  2022 ..
drwxr-xr-x  3 ansar  staff    96B Dec 15 10:18 cert-manager
drwxr-xr-x  3 ansar  staff    96B Dec 21 16:47 kube-prometheus-stack
drwxr-xr-x  3 ansar  staff    96B Oct 14 08:55 stash
drwxr-xr-x  3 ansar  staff    96B Dec  9 09:00 traefik

☸ k0s-cluster in home-ops on  master [$!?] via 🐍 v3.11.6 (venv)
❯ ls -lah flux/crds/traefik
total 8
drwxr-xr-x  3 ansar  staff    96B Dec  9 09:00 .
drwxr-xr-x  6 ansar  staff   192B Dec 30 20:02 ..
-rw-r--r--  1 ansar  staff   618B Dec 30 19:46 crds.yaml
```

and the `crds-traefik`:
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: traefik-source
  namespace: flux-system
spec:
  interval: 12h
  url: https://github.com/traefik/traefik-helm-chart.git
  ref:
    # renovate: registryUrl=https://helm.traefik.io/traefik chart=traefik
    tag: v26.0.0
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/traefik/crds
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds-traefik
  namespace: flux-system
spec:
  interval: 30m
  prune: false
  wait: true
  sourceRef:
    kind: GitRepository
    name: traefik-source
```
