### ISSUE TITLE
Support GitRepository for HelmRelease sources

### ISSUE THREAD

**Issue by tropnikovvl** [allenporter/flux-local#616]
Hello!

I use flux-local as testing for my flux setup and getting an error.

```
FAILED clusters/devops::apps-stack::nexus/nexus - flux_local.exceptions.HelmException: Unable to find HelmRepository for flux-system-flux-system/./helm-charts/nexus-repository-manager for HelmRelease nexus (0 other HelmRepositories in --path)
```

I use some HelmReleases that link not to the helm repository, but to the git repository since they are in git.

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: nexus
  namespace: nexus
spec:
  chart:
    spec:
      chart: ./helm-charts/nexus-repository-manager
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  releaseName: nexus
```

Is it possible to expand the list of possible links for a HelmRelease?

**Comment by allenporter** [comment]
Does that work in production? The chart name isn't a path but a kubernetes resource name so it doesn't look like a chart name format I've ever seen.

**Comment by allenporter** [comment]
I see, I understand your comment now, apologies.

No that is not supported. Flux-local doesn't how to map that git repository to a local path and doesn't download for repos when run from the cli.

If this repo is local I could see it being made to work with '--sources'.  Does it work to run the 'helm template' locally on a chart specified like that? I'm not familiar with git backed charts, but if it's possible to expand with that cli then there may be a way to support this.

**Comment by allenporter** [comment]
The next steps needed to support this would be:
- an example helm chart that can be included in a GitRepository for testing (only supporting the local repository)
- an example `helm template` command line to render the chart

I'm currently not looking into this, but if someone provided the above two things that could make it easier to get started adding support for this in flux-local.

**Comment by tropnikovvl** [comment]
```
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  interval: 5m0s
  url: https://github.com/prometheus-community
  ref:
    branch: main
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: blackbox-exporter
  namespace: default
spec:
  chart:
    spec:
      chart: ./charts/prometheus-blackbox-exporter
      sourceRef:
        kind: GitRepository
        name: prometheus-community
        namespace: flux-system
  releaseName: blackbox-exporter
```
