### ISSUE TITLE
HelmRelease Error: template due to substituteFrom not being supported

### ISSUE THREAD

**Issue by tropnikovvl** [allenporter/flux-local#617]
Hello!

I use flux-local as a github action to view the diff between versions of helm releases.

I encountered a problem that it is impossible to template the parameters that I pass as flux variables.

```
flux_local.exceptions.HelmException: Command 'helm template external-dns flux-system-bitnami/external-dns --namespace external-dns --skip-crds --skip-tests --api-versions policy/v1/PodDisruptionBudget --version 7.1.0 --values /tmp/tmp1fe8o8lo/external-dns-external-dns-values.yaml --registry-config /dev/null --repository-cache /tmp/tmp40mhc7f7 --repository-config /tmp/tmp1fe8o8lo/repository-config.yaml' failed with return code 1
Error: template: external-dns/templates/dep-ds.yaml:133:29: executing "external-dns/templates/dep-ds.yaml" at <.Values.domainFilters>: range can't iterate over ${EXTERNAL_DNS_DONAINS}
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  chart:
    spec:
      chart: external-dns
      version: 7.1.0
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  releaseName: external-dns
  values:
    domainFilters: ${EXTERNAL_DNS_DONAINS}
```

Is it possible to add to your product the ability to pass parameters to it during startup in order to override flux variables?

For example:

```
flux-local test --path clusters/dev --enable-helm -v --parametes EXTERNAL_DNS_DONAINS=["foo.com", "bar.com"]
```

**Comment by allenporter** [comment]
How do you configure these variables in production flux? (Link to docs could help me understand).

Seems reasonable to try and support something like this.

**Comment by allenporter** [comment]
If possible I'd like 'flux build' or 'kustomize' to do the expansion so looking for a built in mechanism to hook into here.

**Comment by tropnikovvl** [comment]
It is https://fluxcd.io/flux/components/kustomize/kustomizations/#post-build-variable-substitution

How it works for me.

I create a configmap when creating a cluster with a set of parameters

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-cluster-settings
  namespace: flux-system
data:
  CLUSTER_NAME: test
  AWS_REGION: eu-central-1
  EXTERNAL_DNS_DONAINS: ["foo.com"]
```

then these configs are used below

```
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: base-stack
  namespace: flux-system
spec:
  interval: 3h
  retryInterval: 5m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/base-stack
  prune: true
  wait: true
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-cluster-settings
```
