### ISSUE TITLE
Test does not work with OCI repositories

### ISSUE THREAD

**Issue by tropnikovvl** [allenporter/flux-local#637]
I'm using [this](https://github.com/hiddenmarten/harbor-project-proxy) project and the test fails on it.
[Flux docs](https://github.com/hiddenmarten/harbor-project-proxy).

```
flux-local test --path clusters/my-cluster --enable-helm -v
```

```
E           flux_local.exceptions.HelmException: Command 'helm template harbor-project-proxy oci://ghcr.io/hiddenmarten/harbor-project-proxy --namespace harbor --skip-crds --skip-tests --version 0.0.1 --values /var/folders/dr/8ck5qq7x1qs12dr6ccwjq2280000gn/T/tmp5ob58gxn/harbor-harbor-project-proxy-values.yaml --registry-config /dev/null --repository-cache /var/folders/dr/8ck5qq7x1qs12dr6ccwjq2280000gn/T/tmpnz52qm_3 --repository-config /var/folders/dr/8ck5qq7x1qs12dr6ccwjq2280000gn/T/tmp5ob58gxn/repository-config.yaml' failed with return code 1
E           Error: failed to authorize: failed to fetch oauth token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Ahiddenmarten%2Fharbor-project-proxy%3Apull&service=ghcr.io: 403 Forbidden
```

```
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hiddenmarten
  namespace: flux-system
spec:
  type: "oci"
  interval: 3h
  url: oci://ghcr.io/hiddenmarten
  timeout: 3m
```

```
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: harbor-project-proxy
  namespace: harbor
spec:
  chart:
    spec:
      chart: harbor-project-proxy
      version: 0.0.1
      sourceRef:
        kind: HelmRepository
        name: hiddenmarten
        namespace: flux-system
  releaseName: harbor-project-proxy
```
