### ISSUE TITLE
Problem with external gitRepository

### ISSUE THREAD

**Issue by yotles** [allenporter/flux-local#753]
@allenporter First of all thank you for such amazing tool! At first glance it could to resolve a lot of my issues during work with flux and gitops scheme. 

But I cannot find the way to work properly. I have more or less standart  platform admin repo with name conf:

```
tree conf
├── apps
│   ├── dev
│   └── prod
├── archived
│   ├── dev
│   └── prod
├── clusters
│   ├── dev
│   └── prod
└── infrastructure
    ├── archived
    ├── dev
    └── prod
```

And kustomizations within flux-system accessible ok with `--sources`:
```
flux-local  get ks --path ./clusters/dev --source flux-system
NAME              PATH
apps              apps/dev
flux-system       clusters/dev
infrastructure    infrastructure/dev
```

But I cannot figure out how to get work it with app which configured with external git repository. My manifests:

```
cat ./infrastructure/dev/app1/gitrepository/kustomize.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app1
  namespace: app1
spec:
  interval: 1m0s
  path: ./base
  prune: true
  sourceRef:
    kind: GitRepository
    name: app1
    namespace: app1
  serviceAccountName: app1

cat ./infrastructure/dev/app1/gitrepository/git.yaml
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: app1
  namespace: app1
spec:
  interval: 1m0s
  ref:
    branch: dev
  secretRef:
    name: flux-deploy-app1
  url: https://gitlab.xxx.xxx/okd/apps/infrastructure/app1.git

Such repository saved with path:

apps/infrastructure/app1/

base
├── imagestream
├── secrets
├── values
└── vault

```
And what I get:
```
 flux-local get ks --path ./infrastructure/dev/app1 --source app1
flux-local error:  Kustomization 'app1/app1-kustomization' path field 'base' is not a directory: /conf/base
```
but in my case `/conf/base` is not correct path, in some way it should look into apps/infrastructure/app1/base. Could you please clarify is it possible to work with flux-local in such manner? 

Thanks!

**Comment by allenporter** [comment]
Yes, this is not currently supported, as the tool will not go out and clone external repos. You may be able to get something working by cloning the external repos yourself and using the --sources flag ([details](https://github.com/allenporter/flux-local/blob/baafa32e28dd325c157bfbeb4aad491a085f6d1c/flux_local/tool/selector.py#L57)) to map the name of a git repo source to a local path.

**Comment by allenporter** [comment]
From the Home Operations discord we see that its possible to have a GitRepository point at the root and cause duplicate objects to be added.

(1) We should prevent duplicate objects from being added
(2) We should consider other approaches for this. Right now --sources can work but maybe we need a default behavior that warns, or a suggestion was to have a flag to just do the full git repo expansion. it will be slow, but maybe ok for experimental feature

**Comment by allenporter** [comment]
Example from our discussion https://github.com/WolfeCub/home-ops/blob/8a836096d0084612c083013d69982449e2c94155/kubernetes/crds/traefik/crds.yaml#L19

**Comment by chrede88** [comment]
I want to add my two cents to this. I just went through a similar issue as OP, where I'm getting strange outputs from `flux-local diff` when adding external gitrepositories.

Here is what I've done:
1) Added an external `Gitrepository` and a `flux kustomization` pointing at the new git repo.
2) When running `flux-local diff` on my PR, flux-local generates some strange (and not correct) output. This seems to be related to the `.spec.path` field in the kustomization, which in my case is not set. flux-local then somehow assumes the path is the path to my main repo kustomizations, which leads to changed labels in these top-level kustomizations (as far as the flux-local output). The changes doesn't actually happen in reality, but this extra output threw me off for some time, while trying to track down this.

The PR is this one: https://github.com/chrede88/home-ops/pull/494
Notice that the two last entries are not related to the changed files. The first label is changed compared to the actual kustomizations on my cluster (also after merging).

I understand that supporting external sources is a large change to the code base, but maybe skipping external sources is better than the current implimentation.

**Comment by allenporter** [comment]
Thanks for that detail. Yes, that is in line with what was intended by "(1)" in https://github.com/allenporter/flux-local/issues/753#issuecomment-2724726882 but your wording is much better.

**Comment by chrede88** [comment]
Yeah, I can see why that would be hard to guess.
We might be able to do this by looking at labels. Looking at the two `GitRepository` manifests I've defined in my cluster, the `GitRepository` that is generated by `Flux` on bootstrap has the following labels:

```yaml
labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/managed-by: flux-operator
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.5.1
    fluxcd.controlplane.io/name: flux
    fluxcd.controlplane.io/namespace: flux-system
```
The first two labels are related to running the `flux-operator`,so they're not general enough. But I think the third label might be useful here. The `GitRepository` I defined myself only have the following labels:

```yaml
labels:
    app.kubernetes.io/name: cilium-crd
    kustomize.toolkit.fluxcd.io/name: cilium-crd
    kustomize.toolkit.fluxcd.io/namespace: flux-system
```
The first is a label I've defined and the last two are added by kustomize controller. Now, I can't verify if all source types (S3 buckets etc) that's used to hold the manifests for flux have this label (`app.kubernetes.io/part-of: flux`), but if it's the case then I think we should be able to assume that this is the "local" repo.
