### ISSUE TITLE
Flux operator - GHA issue

### ISSUE THREAD

**Issue by chrede88** [allenporter/flux-local#806]
I recently switched to use the [Flux operator](https://github.com/controlplaneio-fluxcd/flux-operator). Since then, the `flux-local diff` GHA I'm running on PR's in the repo have failed to produce an output. It looks like the `steps.diff.outputs.diff` is empty, but the `diff` action exits without errors.

I've looked through the debug logs, but I can't see anything that helps me figure out what's wrong.
Maybe the current version of `flux-local` isn't compatible with the operator?

Here is a recent run with `debug: true`: [https://github.com/chrede88/home-ops/actions/runs/11939162030/job/33279075345?pr=275](https://github.com/chrede88/home-ops/actions/runs/11939162030/job/33279075345?pr=275)

I'm running the latest version of `flux-local`: 6.0.2

**Comment by chrede88** [comment]
The layout is basically the same, the main difference is that the main `kustomization` is now (sort of) put into the new type `FluxInstance`. Essentially, this was the main `kustomization` I had before the switch: https://github.com/chrede88/home-ops/blob/07a305ecf0f2988a38514ef6aaf987530f10384d/cluster/kubernetes/flux-system/gotk-sync.yaml
This info is now put into the `spec.sync` in the `FluxInstance`: https://github.com/chrede88/home-ops/blob/07a305ecf0f2988a38514ef6aaf987530f10384d/cluster/kubernetes/flux-system/flux/flux-instance/instance.yaml#L21

I guess this cuts the kustomization path used by `flux-local`, which means it never discovers the rest of the repo (after the `FluxInstance`).

In the GHA I feed the `diff` the following:
```yaml
- uses: allenporter/flux-local/action/diff@6.0.2
        id: diff
        with:
          live-branch: main
          path: cluster/kubernetes/flux-system
          resource: ${{ matrix.resource }}
          debug: true
```

Maybe it would work if I change the path to `cluster/kubernetes/`, as this was the `path` defined in the old main `kustomization`.
