### ISSUE TITLE
Add support for Flux ResourceSets

### ISSUE THREAD

**Issue by allenporter** [allenporter/flux-local#861]

**Comment by crabique** [comment]
This would really be a great feature!


At the moment, it is possible to test the `rset`/`rsip` stuff locally with `flux-operator build rset` and store the output in a temp directory, then do something like this in there to get all the `HelmReleases`:
```
flux-local get cluster -o json | jq -r '.clusters[].kustomizations[].helm_releases[].name'
``` 

Aand then `flux-local build hr {}` every one of them to actually see the rendered application manifests.

But with this approach you have to manually find and explicitly specify all the `rsips` for every `rset`, and then there's the temporary directory with the resulting `HelmReleases` where you have to define a dummy root `Kustomization` like this so that `flux-local` even detects it as a "cluster":

```
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./"
```
