### ISSUE TITLE
HelmRelease ValuesFrom dot notation problem

### ISSUE THREAD

**Issue by Lingkar** [allenporter/flux-local#870]
I am trying to set a specific annotation of which the name includes dots, which need to be escaped.
The docs show that the following characters should be escaped.
https://fluxcd.io/flux/components/helm/helmreleases/#values-references

![Image](https://github.com/user-attachments/assets/7d30e9bd-6b59-4ea7-ae2c-bffba57dbd50)

The example at the bottom is compatible with FluxCD, however flux-local gives the following error:
```
/app $ flux-local build hr -n velero velero --path /git/azure-pipelines/cluster-entries/jbui-cluster-dev/
Unable to find Secret velero/velero-client-identity-id referenced
flux-local error:  Command 'helm template velero velero-vmware-tanzu/velero --namespace velero --repository-cache /tmp/tmp59hve1oh --repository-config /tmp/tmp1fskwhc0/repository-config.yaml --registry-config /dev/null --skip-crds --skip-tests --version 8.3.0 --values /tmp/tmp1fskwhc0/velero-velero-values.yaml' failed with return code 1
Error: YAML parse error on velero/templates/serviceaccount-server.yaml: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal object into Go struct field .metadata.annotations of type string

Use --debug flag to render out invalid YAML
```

At the moment I have been unable to inspect the generated values file in the /tmp directory.

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
spec:
  releaseName: velero
  chart:
    spec:
      chart: velero
      reconcileStrategy: ChartVersion
      version: "8.3.0"
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
  interval: 1m0s
  valuesFrom:
    - kind: ConfigMap
      name: values-velero
    - kind: ConfigMap
      name: values-velero
      valuesKey: env-values.yaml
    - kind: Secret
      name: velero-client-identity-id
      targetPath: serviceAccount.server.annotations.azure\.workload\.identity/client-id
      valuesKey: CLIENT_ID
```
