### ISSUE TITLE
Missing output for diff command with reused OCIRepository

### ISSUE THREAD

**Issue by ansarhun** [allenporter/flux-local#945]
I have a setup where I reuse the same `OCIRepository` for multiple `HelmRelease`. When I update the version of the `OCIRepository` it will only show one (last?) `HelmRelease` as a diff.

E.g.:
```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: app-template-4
  namespace: flux-system
spec:
  interval: 15m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/bjw-s-labs/helm/app-template
  ref:
    tag: "4.1.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: karakeep
  namespace: apps
spec:
  interval: 15m
  timeout: 15m
  chartRef:
    kind: OCIRepository
    name: app-template-4
    namespace: flux-system
  values:
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: unifi-controller
  namespace: unifi
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: app-template-4
    namespace: flux-system
  values:
```

Running ` flux-local diff hr --path ./clusters/home -A` will only show changes from the unifi-controller
